global:
  resolve_timeout: 5m
  smtp_smarthost: "smtp.example.com:587"
  smtp_from: "alerts@aurora-sun.example.com"
  smtp_auth_username: "alerts@aurora-sun.example.com"
  smtp_auth_password: "PLACEHOLDER_PASSWORD"
  smtp_require_tls: true

route:
  group_by: ["alertname", "job"]
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: "email-alerts"

receivers:
  - name: "email-alerts"
    email_configs:
      - to: "admin@aurora-sun.example.com"
        send_resolved: true

inhibit_rules:
  - source_match:
      severity: "critical"
    target_match:
      severity: "warning"
    equal: ["alertname", "instance"]
